apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gu36an5mw-python
  janus-idp.io/tekton: gu36an5mw-python
  backstage.io/kubernetes-id: gu36an5mw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gu36an5mw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
