apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gu36an5mw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gu36an5mw-python 
  name: gu36an5mw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gu36an5mw-python 
